name: Deploy Spring Boot Microservice

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: dianaoviedo4/microservice:users-v1 # user de dockerhub
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar aplicación con Maven
        run: |
          mvn clean package -DskipTests

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y etiquetar imagen
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Actualizar manifiestos de Kubernetes
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:prod-$TAG|" k8s/deployment.yaml
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:dev-$TAG|" k8s/deployment.yaml
          fi

      - name: Subir cambios a repositorio GitOps
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image tag"
          branch: develop  # O develop según el entorno